### ISSUE TITLE
Error 500 for captcha image on production

### ISSUE THREAD

**Issue by Postroutine** [mbi/django-simple-captcha#137]
Hello.
I simply follow the django-simple-captcha. When I use it on dev, no problem, but when the website is in production, I got an error 500 on the captcha image.

**Comment by Postroutine** [comment]
Fixed by re-installing Pillow after check all system dependencies

**Comment by narutobaka** [comment]
Hi 

I encounter same problem on CentOS 7 :

update python-pillow-2.0.0-20.gitd1c6db8.el7_7.x86_64 broke django-simple-captcha
And I get error 500 for captcha image

I try to downgrade to python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64 but still have the problem.

trace of error : 

Internal Server Error: /captcha/image/7db458a9a20a4dac676c1bb9db4bd5a24c366f15/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/site-packages/captcha/views.py", line 89, in captcha_image
    charimage = charimage.rotate(random.randrange(*settings.CAPTCHA_LETTER_ROTATION), expand=0, resample=Image.BICUBIC)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 1403, in rotate
    return self._new(self.im.rotate(angle, resample))
AttributeError: 'ImagingCore' object has no attribute 'rotate'

@ghost did you do something spécial when roll back to python-pillow-2.0.0-19.gitd1c6db8.el7.x86_64 ? to get back your captcha?

thx
